ConfigVars = {}
ConfigVars ['DownloadURLS'] = 1
ConfigVars['MockForFE'] = 0
# 0 = Dont log anything
# 1 = Write to log only
# 2 = Write to console only
# 3 = Write to log and console
ConfigVars ['LogLevel'] = 2
ConfigVars ['LogFile'] = 'log.txt'
